services:
  mysql:
    image: mysql:8.0.42
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped    
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}

  zoneminder:
    image: zoneminder
    build: .
    shm_size: 1G
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./cache:/var/cache/zoneminder
      - ./zm-log:/var/log/zm
      - ./apache2-log:/var/log/apache2
      - ./start.sh:/start.sh
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql

volumes:
  mysql-data:
